package com.emental.dao.entity;

import java.io.Serializable;

public class EmMoodDiary implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_MOOD_DIARY.DATA_ID
     *
     * @mbg.generated
     */
    private String dataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_MOOD_DIARY.USERNAME
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_MOOD_DIARY.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_MOOD_DIARY.MOOD_STATUS
     *
     * @mbg.generated
     */
    private String moodStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_MOOD_DIARY.CREATE_DATE
     *
     * @mbg.generated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EM_MOOD_DIARY
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_MOOD_DIARY.DATA_ID
     *
     * @return the value of EM_MOOD_DIARY.DATA_ID
     *
     * @mbg.generated
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_MOOD_DIARY.DATA_ID
     *
     * @param dataId the value for EM_MOOD_DIARY.DATA_ID
     *
     * @mbg.generated
     */
    public void setDataId(String dataId) {
        this.dataId = dataId == null ? null : dataId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_MOOD_DIARY.USERNAME
     *
     * @return the value of EM_MOOD_DIARY.USERNAME
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_MOOD_DIARY.USERNAME
     *
     * @param username the value for EM_MOOD_DIARY.USERNAME
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_MOOD_DIARY.CONTENT
     *
     * @return the value of EM_MOOD_DIARY.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_MOOD_DIARY.CONTENT
     *
     * @param content the value for EM_MOOD_DIARY.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_MOOD_DIARY.MOOD_STATUS
     *
     * @return the value of EM_MOOD_DIARY.MOOD_STATUS
     *
     * @mbg.generated
     */
    public String getMoodStatus() {
        return moodStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_MOOD_DIARY.MOOD_STATUS
     *
     * @param moodStatus the value for EM_MOOD_DIARY.MOOD_STATUS
     *
     * @mbg.generated
     */
    public void setMoodStatus(String moodStatus) {
        this.moodStatus = moodStatus == null ? null : moodStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_MOOD_DIARY.CREATE_DATE
     *
     * @return the value of EM_MOOD_DIARY.CREATE_DATE
     *
     * @mbg.generated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_MOOD_DIARY.CREATE_DATE
     *
     * @param createDate the value for EM_MOOD_DIARY.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EM_MOOD_DIARY
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dataId=").append(dataId);
        sb.append(", username=").append(username);
        sb.append(", content=").append(content);
        sb.append(", moodStatus=").append(moodStatus);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}