package com.emental.dao.entity;

import java.io.Serializable;

public class EmUserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_USER_INFO.DATA_ID
     *
     * @mbg.generated
     */
    private String dataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_USER_INFO.USERNAME
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_USER_INFO.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_USER_INFO.REAL_NAME
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_USER_INFO.BIRTH_DATE
     *
     * @mbg.generated
     */
    private String birthDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_USER_INFO.GENDER
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_USER_INFO.EMAIL_ADDRESS
     *
     * @mbg.generated
     */
    private String emailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_USER_INFO.PHONE_NUMBER
     *
     * @mbg.generated
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_USER_INFO.PERSON_INFO
     *
     * @mbg.generated
     */
    private String personInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_USER_INFO.CREATE_DATE
     *
     * @mbg.generated
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_USER_INFO.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EM_USER_INFO.NOTIFY_FLAG
     *
     * @mbg.generated
     */
    private String notifyFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EM_USER_INFO
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_USER_INFO.DATA_ID
     *
     * @return the value of EM_USER_INFO.DATA_ID
     *
     * @mbg.generated
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_USER_INFO.DATA_ID
     *
     * @param dataId the value for EM_USER_INFO.DATA_ID
     *
     * @mbg.generated
     */
    public void setDataId(String dataId) {
        this.dataId = dataId == null ? null : dataId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_USER_INFO.USERNAME
     *
     * @return the value of EM_USER_INFO.USERNAME
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_USER_INFO.USERNAME
     *
     * @param username the value for EM_USER_INFO.USERNAME
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_USER_INFO.PASSWORD
     *
     * @return the value of EM_USER_INFO.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_USER_INFO.PASSWORD
     *
     * @param password the value for EM_USER_INFO.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_USER_INFO.REAL_NAME
     *
     * @return the value of EM_USER_INFO.REAL_NAME
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_USER_INFO.REAL_NAME
     *
     * @param realName the value for EM_USER_INFO.REAL_NAME
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_USER_INFO.BIRTH_DATE
     *
     * @return the value of EM_USER_INFO.BIRTH_DATE
     *
     * @mbg.generated
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_USER_INFO.BIRTH_DATE
     *
     * @param birthDate the value for EM_USER_INFO.BIRTH_DATE
     *
     * @mbg.generated
     */
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate == null ? null : birthDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_USER_INFO.GENDER
     *
     * @return the value of EM_USER_INFO.GENDER
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_USER_INFO.GENDER
     *
     * @param gender the value for EM_USER_INFO.GENDER
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_USER_INFO.EMAIL_ADDRESS
     *
     * @return the value of EM_USER_INFO.EMAIL_ADDRESS
     *
     * @mbg.generated
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_USER_INFO.EMAIL_ADDRESS
     *
     * @param emailAddress the value for EM_USER_INFO.EMAIL_ADDRESS
     *
     * @mbg.generated
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress == null ? null : emailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_USER_INFO.PHONE_NUMBER
     *
     * @return the value of EM_USER_INFO.PHONE_NUMBER
     *
     * @mbg.generated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_USER_INFO.PHONE_NUMBER
     *
     * @param phoneNumber the value for EM_USER_INFO.PHONE_NUMBER
     *
     * @mbg.generated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_USER_INFO.PERSON_INFO
     *
     * @return the value of EM_USER_INFO.PERSON_INFO
     *
     * @mbg.generated
     */
    public String getPersonInfo() {
        return personInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_USER_INFO.PERSON_INFO
     *
     * @param personInfo the value for EM_USER_INFO.PERSON_INFO
     *
     * @mbg.generated
     */
    public void setPersonInfo(String personInfo) {
        this.personInfo = personInfo == null ? null : personInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_USER_INFO.CREATE_DATE
     *
     * @return the value of EM_USER_INFO.CREATE_DATE
     *
     * @mbg.generated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_USER_INFO.CREATE_DATE
     *
     * @param createDate the value for EM_USER_INFO.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_USER_INFO.STATUS
     *
     * @return the value of EM_USER_INFO.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_USER_INFO.STATUS
     *
     * @param status the value for EM_USER_INFO.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EM_USER_INFO.NOTIFY_FLAG
     *
     * @return the value of EM_USER_INFO.NOTIFY_FLAG
     *
     * @mbg.generated
     */
    public String getNotifyFlag() {
        return notifyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EM_USER_INFO.NOTIFY_FLAG
     *
     * @param notifyFlag the value for EM_USER_INFO.NOTIFY_FLAG
     *
     * @mbg.generated
     */
    public void setNotifyFlag(String notifyFlag) {
        this.notifyFlag = notifyFlag == null ? null : notifyFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EM_USER_INFO
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dataId=").append(dataId);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", realName=").append(realName);
        sb.append(", birthDate=").append(birthDate);
        sb.append(", gender=").append(gender);
        sb.append(", emailAddress=").append(emailAddress);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", personInfo=").append(personInfo);
        sb.append(", createDate=").append(createDate);
        sb.append(", status=").append(status);
        sb.append(", notifyFlag=").append(notifyFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}