spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:\Users\mu20101\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\tmp\sqlite-autoconf-3320300\emental.db
  mail:
    host: smtp.qq.com
    username: 649791555@qq.com
    password: lxkaexfxhrwibeff
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mail:
  fromMail:
    addr: ADU Team<649791555@qq.com>

server:
  port: 8080

mybatis:
  type-aliases-package: com.emental.dao.entity
  configuration:
    map-underscore-to-camel-case: true