spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:\Users\mu20101\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\tmp\sqlite-autoconf-3320300\emental.db
  mail:
    host: smtp.office365.com
    username: mu20101@outlook.com
    password: shayezhige00
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mail:
  fromMail:
    addr: E-mental Team<mu20101@outlook.com>

server:
  port: 8080

mybatis:
  type-aliases-package: com.emental.dao.entity
  configuration:
    map-underscore-to-camel-case: true